# run: conda env create --file environment.yml
name: lc-reconcile
channels:
  - conda-forge
dependencies:
  - python=3.10 # Pinned because 3.11 has issues
  - flask
  - requests
  - requests-cache # Optional, but recommended
  - rapidfuzz

